import type { Metadata } from "next";
import localFont from "next/font/local";
import React from "react";

import MotionWrapper from "@/components/layouts/MotionWrapper";
import Footer from "@/components/layouts/footer/Footer";
import { Toaster } from "@/components/ui/toaster";

import "./globals.css";

const lineSeed = localFont({
  src: [
    {
      path: "../public/LINESeedJP_OTF_Bd.woff2",
      style: "normal",
      weight: "600",
    },
    {
      path: "../public/LINESeedJP_OTF_Eb.woff2",
      style: "normal",
      weight: "800",
    },
    {
      path: "../public/LINESeedJP_OTF_Rg.woff2",
      style: "normal",
      weight: "300",
    },
    {
      path: "../public/LINESeedJP_OTF_Th.woff2",
      style: "normal",
      weight: "100",
    },
  ],
});

export const metadata: Metadata = {
  title: "Aoyama Kazuki's Portfolio Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  // modal,
}: Readonly<{
  children: React.ReactNode;
  // modal: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="scroll-pt-36 scroll-smooth">
      <body className={lineSeed.className + " flex flex-col min-h-screen"}>
        <div className="grow">
          <MotionWrapper>
            <div>
              {children}
              {/* {modal} */}
            </div>
          </MotionWrapper>
        </div>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
