import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import MotionWrapper from "./_components/layouts/MotionWrapper";
import Footer from "./_components/layouts/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

const lineSeed = localFont({
  src: [
    {
      path: "./LINESeedJP_OTF_Bd.woff2",
      style: "normal",
      weight: "600",
    },
    {
      path: "./LINESeedJP_OTF_Eb.woff2",
      style: "normal",
      weight: "800",
    },
    {
      path: "./LINESeedJP_OTF_Rg.woff2",
      style: "normal",
      weight: "300",
    },
    {
      path: "./LINESeedJP_OTF_Th.woff2",
      style: "normal",
      weight: "100",
    },
  ],
});

export const metadata: Metadata = {
  title: "Aoyama Kazuki's Portfolio Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="scroll-smooth scroll-pt-36">
      <body className={lineSeed.className + " flex flex-col min-h-screen"}>
        <div className="flex-grow">
          <MotionWrapper>
            <div>
              {children}
              {modal}
            </div>
          </MotionWrapper>
        </div>
        <Footer />
      </body>
    </html>
  );
}
